#!/usr/bin/env bash

npx tsc

for file in *.js; do
	if [[ $file == "tsconfig.json" ]];
	then
		continue
	fi
  uglifyjs "$file" -c -m  -o ./"$file" --source-map 'filename'
  echo minified: "$file"
done
