#!/usr/bin/env bash

npx ava ./test/**/*

#npx ava ./test/alt.ts
#npx ava ./test/compose.ts
#npx ava ./test/container.ts
#npx ava ./test/curry.ts
#npx ava ./test/either.ts
#npx ava ./test/empty.ts
#npx ava ./test/getPropOrElse.ts
#npx ava ./test/io.ts
#npx ava ./test/maybe.ts
#npx ava ./test/partial.ts
#npx ava ./test/pipe.ts
#npx ava ./test/isEmpty.ts
#npx ava ./test/isBoolean.ts
#npx ava ./test/lift.ts
#npx ava ./test/seq.ts
